[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."send-balance-reminder"]
  schedule = "@hourly"

[[redirects]]
  from = "/pay"
  to = "/.netlify/functions/pay"
  status = 200

[[redirects]]
  from = "/admin-reminders"
  to = "/admin-reminders.html"
  status = 200
